Prevent stack trace collection from blocking if read blocks after select
thoughtspot/threadstacks pull request #1
Opened 2018-02-28 00:22 UTC by bothra90

As per https://stackoverflow.com/questions/5351994/will-read-ever-block-after-select, a
`read` can block on a file descriptor even if a previous `select` on the `fd` returned with `FD_ISSET` being true for the `fd`.
Under such a scenario, the thread collecting stacktraces can block forever.

2018-03-01 14:10 UTC, nipun-sehrawat requested changes

2018-03-01 14:10 UTC, nipun-sehrawat commented on threadstacks/signal_handler.cc
> +    if (e.empty()) {
Shouldn't this be e.tids.empty()? Also, in this case, let's populate ss with "No threads".

2018-03-01 14:12 UTC, nipun-sehrawat commented
Great catch, @bothra90!

2018-03-02 01:12 UTC, bothra90 commented
Updated after addressing review comments

2018-03-02 11:53 UTC, nipun-sehrawat approved these changes
LGTM

2018-03-02 11:54 UTC, merged